version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres