default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRESQL_PORT', '5432') %>
  pool: 5

development:
  <<: *default
  database: vinyl_store_development

staging:
  <<: *default
  database: vinyl_store_staging

test:
  <<: *default
  database: vinyl_store_test

production:
  <<: *default
  database: vinyl_store_production
